package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import modelo.TipoDeAlojamiento;

/**
 * 
 * author BERJANO MUÑOZ, RAFAEL
 * author BOZA VILLAR, RICARDO
 * author CALIXTO DEL HOYO, JUAN
 * author GARCÍA MARCHENA, ÁLVARO
 */
public class VentanaAlojamientosAlta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAlojamientosAlta
     */
    public VentanaAlojamientosAlta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ubicacionGrupo = new javax.swing.ButtonGroup();
        panelNorte = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        panelCentro = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        poblacionLabel = new javax.swing.JLabel();
        provinciaLabel = new javax.swing.JLabel();
        tipoAlojamientoLabel = new javax.swing.JLabel();
        ubicacionLabel = new javax.swing.JLabel();
        capacidadLabel = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        poblacionTxt = new javax.swing.JTextField();
        tipoAlojamientoComboBox = new javax.swing.JComboBox();
        panelRadioButtons = new javax.swing.JPanel();
        enPoblacionRadioButton = new javax.swing.JRadioButton();
        aisladoRadioButton = new javax.swing.JRadioButton();
        capacidadTxt = new javax.swing.JTextField();
        provinciaTxt = new javax.swing.JTextField();
        panelSur = new javax.swing.JPanel();
        mensajeLabel = new javax.swing.JLabel();
        nuevoButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento de alojamientos");
        setResizable(false);

        panelNorte.setBackground(java.awt.Color.white);
        panelNorte.setName("panelNorte"); // NOI18N
        panelNorte.setLayout(new java.awt.BorderLayout());

        tituloLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tituloLabel.setText("Alquiler de alojamientos rurales (RuralHome)");
        tituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNorte.add(tituloLabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setBackground(java.awt.Color.white);
        panelCentro.setName("panelCentro"); // NOI18N
        panelCentro.setLayout(new java.awt.GridBagLayout());

        nombreLabel.setText("Nombre:");
        panelCentro.add(nombreLabel, new java.awt.GridBagConstraints());

        poblacionLabel.setText("Población:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelCentro.add(poblacionLabel, gridBagConstraints);

        provinciaLabel.setText("Provincia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelCentro.add(provinciaLabel, gridBagConstraints);

        tipoAlojamientoLabel.setText("Tipo Alojamiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        panelCentro.add(tipoAlojamientoLabel, gridBagConstraints);

        ubicacionLabel.setText("Ubicación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        panelCentro.add(ubicacionLabel, gridBagConstraints);

        capacidadLabel.setText("Capacidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        panelCentro.add(capacidadLabel, gridBagConstraints);

        nombreTxt.setPreferredSize(new java.awt.Dimension(100, 20));
        panelCentro.add(nombreTxt, new java.awt.GridBagConstraints());

        poblacionTxt.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelCentro.add(poblacionTxt, gridBagConstraints);

        tipoAlojamientoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoAlojamientoComboBox.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        panelCentro.add(tipoAlojamientoComboBox, gridBagConstraints);

        panelRadioButtons.setBackground(java.awt.Color.white);
        panelRadioButtons.setLayout(new java.awt.GridBagLayout());

        enPoblacionRadioButton.setBackground(java.awt.Color.white);
        ubicacionGrupo.add(enPoblacionRadioButton);
        enPoblacionRadioButton.setText("En población");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelRadioButtons.add(enPoblacionRadioButton, gridBagConstraints);

        aisladoRadioButton.setBackground(java.awt.Color.white);
        ubicacionGrupo.add(aisladoRadioButton);
        aisladoRadioButton.setText("Aislado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelRadioButtons.add(aisladoRadioButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCentro.add(panelRadioButtons, gridBagConstraints);

        capacidadTxt.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        panelCentro.add(capacidadTxt, gridBagConstraints);

        provinciaTxt.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCentro.add(provinciaTxt, gridBagConstraints);

        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        panelSur.setBackground(java.awt.Color.white);
        panelSur.setLayout(new java.awt.GridBagLayout());

        mensajeLabel.setText("mensajePrueba");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelSur.add(mensajeLabel, gridBagConstraints);

        nuevoButton.setText("Nuevo");
        panelSur.add(nuevoButton, new java.awt.GridBagConstraints());

        salirButton.setText("Salir");
        panelSur.add(salirButton, new java.awt.GridBagConstraints());

        aceptarButton.setText("Aceptar");
        panelSur.add(aceptarButton, new java.awt.GridBagConstraints());

        cancelarButton.setText("Cancelar");
        panelSur.add(cancelarButton, new java.awt.GridBagConstraints());

        getContentPane().add(panelSur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlojamientosAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlojamientosAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlojamientosAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlojamientosAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAlojamientosAlta().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JRadioButton aisladoRadioButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel capacidadLabel;
    private javax.swing.JTextField capacidadTxt;
    private javax.swing.JRadioButton enPoblacionRadioButton;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelRadioButtons;
    private javax.swing.JPanel panelSur;
    private javax.swing.JLabel poblacionLabel;
    private javax.swing.JTextField poblacionTxt;
    private javax.swing.JLabel provinciaLabel;
    private javax.swing.JTextField provinciaTxt;
    private javax.swing.JButton salirButton;
    private javax.swing.JComboBox tipoAlojamientoComboBox;
    private javax.swing.JLabel tipoAlojamientoLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.ButtonGroup ubicacionGrupo;
    private javax.swing.JLabel ubicacionLabel;
    // End of variables declaration//GEN-END:variables
    
    public JTextField getNombreTxt() { return nombreTxt; }
    public JTextField getPoblacionTxt() { return poblacionTxt; }
    public JTextField getProvinciaTxt() { return provinciaTxt; }
    public JComboBox getTipoAlojamientoComboBox() { return tipoAlojamientoComboBox; }
    public JRadioButton getEnPoblacionRadioButton() { return enPoblacionRadioButton; }
    public JRadioButton getAisladoRadioButton() { return aisladoRadioButton; }
    public ButtonGroup getUbicacionGrupo() { return ubicacionGrupo; }
    public JTextField getCapacidadTxt() { return capacidadTxt; }
    public JLabel getMensajeLabel() { return mensajeLabel; }
    public JButton getNuevoButton() { return nuevoButton; }
    public JButton getSalirButton() { return salirButton; }
    public JButton getAceptarButton() { return aceptarButton; }
    public JButton getCancelarButton() { return cancelarButton; }
}
